version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"       # Puerto para conexiones AMQP
      - "15672:15672"     # Puerto para la interfaz web de administración
    environment:
      RABBITMQ_DEFAULT_USER: admin      # Cambia esto por tu usuario deseado
      RABBITMQ_DEFAULT_PASS: admin  # Cambia esto por tu contraseña deseada
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rabbitmq_net
    restart: unless-stopped

volumes:
  rabbitmq_data:

networks:
  rabbitmq_net:
    driver: bridge
