spring:
  application:
    name: SERVICIO-SINCRONIZACIONES
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
reloj:
  intervalo: 10
server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
